import { MemoizedSelector } from '@ngrx/store';
import { StateWithProduct } from '../product-state';
import { EntityLoaderState } from '../../../state/utils/entity-loader/entity-loader-state';
import { LoaderState } from '../../../state/utils/loader/loader-state';
import { UIProduct } from '../../model/product';
export declare const getProductState: MemoizedSelector<StateWithProduct, EntityLoaderState<UIProduct>>;
export declare const getSelectedProductsFactory: (codes: string[]) => MemoizedSelector<StateWithProduct, UIProduct[]>;
export declare const getSelectedProductStateFactory: (code: string) => MemoizedSelector<StateWithProduct, LoaderState<UIProduct>>;
export declare const getSelectedProductFactory: (code: string) => MemoizedSelector<StateWithProduct, UIProduct>;
export declare const getSelectedProductLoadingFactory: (code: string) => MemoizedSelector<StateWithProduct, boolean>;
export declare const getSelectedProductSuccessFactory: (code: string) => MemoizedSelector<StateWithProduct, boolean>;
export declare const getSelectedProductErrorFactory: (code: string) => MemoizedSelector<StateWithProduct, boolean>;
export declare const getAllProductCodes: MemoizedSelector<StateWithProduct, string[]>;
