import { Action, MetaReducer } from '@ngrx/store';
import { WindowRef } from '../../window/window-ref';
import { StateConfig, StorageSyncType } from '../config/state-config';
export declare function getStorageSyncReducer<T>(winRef: WindowRef, config?: StateConfig): MetaReducer<T, Action>;
export declare function rehydrate<T>(config: StateConfig, winRef: WindowRef): T;
export declare function exists(value: Object): boolean;
export declare function getStorage(storageType: StorageSyncType, winRef: WindowRef): Storage;
export declare function persistToStorage(configKey: string, value: any, storage: Storage): void;
export declare function readFromStorage(storage: Storage, key: string): any;
export declare function isSsr(storage: Storage): boolean;
